export const FETCH_LIST = 'FETCH_LIST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_ERROR = 'FETCH_LIST_ERROR'

export const SAVE_LIST = 'SAVE_LIST'
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS'
export const SAVE_LIST_ERROR = 'SAVE_LIST_ERROR'

export const FETCH_WATCHED = 'FETCH_WATCHED'
export const FETCH_WATCHED_SUCCESS = 'FETCH_WATCHED_SUCCESS'
export const FETCH_WATCHED_ERROR = 'FETCH_WATCHED_ERROR'

export const SAVE_WATCHED = 'SAVE_WATCHED'
export const SAVE_WATCHED_SUCCESS = 'SAVE_WATCHED_SUCCESS'
export const SAVE_WATCHED_ERROR = 'SAVE_WATCHED_ERROR'

export const CLEAR = 'CLEAR'
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const WATCHLIST = 'watchlist'
export const WATCHED = 'watched'

export const SEARCH_MOVIE = 'SEARCH_MOVIE'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'

export const SET_SELECTED_INLIST = 'SET_SELECTED_INLIST'
export const SET_SELECTED_NOTLISTED = 'SET_SELECTED_NOTLISTED'

export const RESET_SELECTED_INLIST = 'RESET_SELECTED_INLIST'
export const RESET_SELECTED_NOTLISTED = 'RESET_SELECTED_NOTLISTED'

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS'
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS'
export const FETCH_MOVIE_DETAILS_ERROR = 'FETCH_MOVIE_DETAILS_ERROR'

export const FETCH_MOVIES_FOR_HOME = 'FETCH_MOVIES_FOR_HOME'
export const FETCH_MOVIES_FOR_HOME_SUCCESS = 'FETCH_MOVIES_FOR_HOME_SUCCESS'
export const FETCH_MOVIES_FOR_HOME_ERROR = 'FETCH_MOVIES_FOR_HOME_ERROR'

export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'

// export const LOGIN_USER = 'LOGIN_USER'
// export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
// export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
// export const REGISTER_USER = 'REGISTER_USER'
// export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
// export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const DELETE_MOVIE = 'DELETE_MOVIE'
