export const FETCH_LIST = 'FETCH_LIST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_ERROR = 'FETCH_LIST_ERROR'

export const ADD_TO_LIST = 'ADD_TO_LIST'
export const MARK_MOVIE_WATCHED = 'MARK_MOVIE_WATCHED'
export const DISCARD_MOVIE = 'DISCARD_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'

export const FETCH_WATCHED = 'FETCH_WATCHED'
export const FETCH_WATCHED_SUCCESS = 'FETCH_WATCHED_SUCCESS'
export const FETCH_WATCHED_ERROR = 'FETCH_WATCHED_ERROR'

export const SEARCH_MOVIE = 'SEARCH_MOVIE'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE'
export const RESET_SELECTED_MOVIE = 'RESET_SELECTED_MOVIE'

export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
